import type { Metadata } from 'next'
import './globals.css'
import Navigation from '@/components/navigation'
import { headers } from 'next/headers'

export const metadata: Metadata = {
    title: {
        template: '%s | Next',
        default: 'Next',
    },
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const hideNavigation = headers().get('x-hide-navigation') === 'true'
    return (
        <html lang="ko">
            <body className="flex flex-col gap-4 items-center">
                {!hideNavigation && <Navigation />}
                {children}
            </body>
        </html>
    )
}
