import type { Metadata } from 'next'
import './globals.css'
import Navigation from '@/components/navigation'

export const metadata: Metadata = {
    title: {
        template: '%s | Next',
        default: 'Next',
    },
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode
    params: { slug: string }
}>) {
    const { slug } = params // 비동기로 처리
    console.log(.join)
    return (
        <html lang="ko">
            <body className="flex flex-col gap-4 items-center">
                {/* {!hideNavigation && <Navigation />} */}
                <Navigation />
                {children}
            </body>
        </html>
    )
}
